# Generated by Django 3.2.5 on 2021-07-25 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0004_auto_20181004_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 21, 26, 14, 518173)),
        ),
    ]
